nc: named capture

| [[file:tests/testthat][tests]]    | [[https://travis-ci.org/tdhock/nc][https://travis-ci.org/tdhock/nc.png?branch=master]]                           |
| [[https://github.com/jimhester/covr][coverage]] | [[https://coveralls.io/github/tdhock/nc?branch=master][https://coveralls.io/repos/tdhock/nc/badge.svg?branch=master&service=github]] |

User-friendly functions for extracting data tables from non-tabular
text using regular expressions.

There are a few differences between nc and [[https://github.com/tdhock/namedCapture][namedCapture]]:
- ICU engine is now supported in addition to PCRE and RE2.
- output is now always a data.frame (namedCapture uses a character
  matrix if no type conversion functions are specified).
- =nc::capture_first_df= does not prefix subject column names to
  capture group column names, whereas
  =namedCapture::df_match_variable= does.
- Internally =nc= uses un-named capture groups, whereas
  =namedCapture= uses named capture groups.
- By default the =nc::capture_first_vec= stops with an error if any
  subjects do not match, whereas =namedCapture::str_match_variable=
  returns NA/missing rows.

** Installation

#+BEGIN_SRC R
if(!require(devtools))install.packages("devtools")
devtools::install_github("tdhock/nc")
#+END_SRC

** Usage overview

There are three main functions provided in nc:

| Subject          | First match         | All matches       |
|------------------+---------------------+-------------------|
| Single string    | NA                  | =capture_all_str= |
| Character vector | =capture_first_vec= | NA                |
| Data frame       | =capture_first_df=  | NA                |

Note that these functions are analogous to the ones in namedCapture,
but all have the =capture_= prefix for easy auto-completion:

| namedCapture           | nc                |
|------------------------+-------------------|
| str_match_variable     | capture_first_vec |
| str_match_all_variable | capture_all_str   |
| df_match_variable      | capture_first_df  |

See my [[https://github.com/tdhock/namedCapture-article][journal paper about namedCapture]] for a usage explanation, and a
detailed comparison with other R regex packages.

** Choice of regex engine

By default, nc uses PCRE. Other options include ICU and RE2.

To tell nc that you would like to use a certain engine, 
#+BEGIN_SRC R
options(nc.engine="RE2")
#+END_SRC

Every function also has an engine argument, e.g.

#+BEGIN_SRC R
  nc::capture_first_vec(
    "foo a\U0001F60E# bar",
    before=".*?",
    emoji="\\p{EMOJI_Presentation}",
    after=".*",
    engine="ICU")
  #>   before emoji after
  #> 1  foo a     😎 # bar
#+END_SRC

