nc: named capture

| [[file:tests/testthat][tests]]    | [[https://travis-ci.org/tdhock/nc][https://travis-ci.org/tdhock/nc.png?branch=master]]                           |
| [[https://github.com/jimhester/covr][coverage]] | [[https://coveralls.io/github/tdhock/nc?branch=master][https://coveralls.io/repos/tdhock/nc/badge.svg?branch=master&service=github]] |

User-friendly functions for extracting data tables from non-tabular
text using regular expressions.

#+BEGIN_SRC R
  food.vec <- c("granny smith apple", "blood orange")
  nc::capture_first_vec(food.vec, type=".*", " ", fruit="orange|apple")
  #>            type  fruit
  #> 1: granny smith  apple
  #> 2:        blood orange
#+END_SRC

** Installation

#+BEGIN_SRC R
install.packages("nc")
## or:
if(!require(devtools))install.packages("devtools")
devtools::install_github("tdhock/nc")
#+END_SRC


** Usage overview

The main functions provided in nc are:

| Subject              | First match             | All matches       |
|----------------------+-------------------------+-------------------|
| Single string        | NA                      | =capture_all_str= |
| Character vector     | =capture_first_vec=     | NA                |
| Data frame chr cols  | =capture_first_df=      | NA                |
| Data frame col names | =capture_melt_single=   | NA                |
| Data frame col names | =capture_melt_multiple= | NA                |

- [[https://cloud.r-project.org/web/packages/nc/vignettes/v1-capture-first.html][Vignette 1]] discusses =capture_first_vec= and =capture_first_df=, and
  =capture_first_melt=, which capture the first match in each of
  several subjects (character vector, data frame character columns).
- [[https://cloud.r-project.org/web/packages/nc/vignettes/v2-capture-all.html][Vignette 2]] discusses =capture_all_str= which captures all matches in
  a single big multi-line subject string. The vignette also shows how
  to use =capture_all_str= on several different multi-line subject
  strings, using data.table =by= syntax.
- [[https://cloud.r-project.org/web/packages/nc/vignettes/v3-capture-melt.html][Vignette 3]] discusses =capture_melt_single= and
  =capture_melt_multiple= which match a regex to the column
  names of a wide data frame, then melt the matching columns. These
  functions are especially useful when more than one separate piece of
  information can be captured from each column name, e.g. the iris
  column names =Petal.Width=, =Sepal.Width=, etc each have two pieces
  of information (flower part and measurement dimension).

** Choice of regex engine

By default, nc uses PCRE. Other options include ICU and RE2.

To tell nc that you would like to use a certain engine, 
#+BEGIN_SRC R
options(nc.engine="RE2")
#+END_SRC

Every function also has an engine argument, e.g.

#+BEGIN_SRC R
  nc::capture_first_vec(
    "foo a\U0001F60E# bar",
    before=".*?",
    emoji="\\p{EMOJI_Presentation}",
    after=".*",
    engine="ICU")
  #>   before emoji after
  #> 1  foo a     😎 # bar
#+END_SRC

** Related work

Going forward I recommend using nc rather than [[https://github.com/tdhock/namedCapture][namedCapture]], which is
an older package that provides [[https://cloud.r-project.org/web/packages/namedCapture/vignettes/v2-recommended-syntax.html][a similar API]]:

| namedCapture           | nc                          |
|------------------------+-----------------------------|
| str_match_variable     | capture_first_vec           |
| str_match_all_variable | capture_all_str             |
| df_match_variable      | capture_first_df            |

For an overview of these functions, see my [[https://github.com/tdhock/namedCapture-article][R journal paper about
namedCapture]] for a usage explanation, and a detailed comparison with
other R regex packages. The main differences between the functions in
=nc= and =namedCapture= are:
- Main =nc= functions all have the =capture_= prefix for easy auto-completion.
- Internally =nc= uses un-named capture groups, whereas =namedCapture=
  uses named capture groups. This allows =nc= to support the ICU
  engine in addition to PCRE and RE2.
- Output in =nc= is always a data.table (=namedCapture= functions
  output either a character matrix or a data.frame).
- =nc::capture_first_df= does not prefix subject column names to
  capture group column names, whereas
  =namedCapture::df_match_variable= does.
- By default the =nc::capture_first_vec= stops with an error if any
  subjects do not match, whereas =namedCapture::str_match_variable=
  returns NA/missing rows.
- Subject names and the capture group named =name= are not treated
  specially (in =namedCapture= they are used for rownames of output).
- =nc::capture_all_str= only supports capturing multiple matches in a
  single subject, whereas =namedCapture::str_match_all_named= supports
  multiple subjects. 
  For multiple subjects, use =DT[, nc::capture_all_str(subject), by]=
  (see [[https://cloud.r-project.org/web/packages/nc/vignettes/v2-capture-all.html][vignette 2]] for more info).

There are some new features in =nc= which are not present in
=namedCapture=:
- =nc::capture_melt_single= inputs a data.frame, tries to match a
  regex to its column names, then melts matching input column names to
  a single output column.
- =nc::capture_first_melt_multiple= inputs a data.frame, tries to
  match a regex to its column names, then melts matching input columns
  to several output columns of different types.
- Helper function =nc::field= is provided for defining patterns (with
  no repetition) that match subjects like variable=value, and create a
  column/group named variable. 
  See [[https://cloud.r-project.org/web/packages/nc/vignettes/v2-capture-all.html][vignette 2]] for more info.

These new features provide functionality similar to packages tidyr,
stats, data.table, reshape, reshape2, cdata, utils, etc. The main
difference is that =nc::capture_melt_*= support named capture regular
expressions with type conversion, which (1) makes it easier to
create/maintain a complex regex, and (2) results in less repetition in
user code. For a detailed comparison see [[https://github.com/tdhock/nc-article][my paper about nc]].
  
