nc: named capture

| [[file:tests/testthat][tests]]    | [[https://travis-ci.org/tdhock/nc][https://travis-ci.org/tdhock/nc.png?branch=master]]                           |
| [[https://github.com/jimhester/covr][coverage]] | [[https://coveralls.io/github/tdhock/nc?branch=master][https://coveralls.io/repos/tdhock/nc/badge.svg?branch=master&service=github]] |

The nc package provides user-friendly functions for extracting data
tables from non-tabular text using regular expressions. 

There are a few differences between nc and [[https://github.com/tdhock/namedCapture][namedCapture]]:
- ICU engine is now supported in addition to PCRE and RE2.
- output is now always a data.frame (namedCapture uses a character
  matrix if no type conversion functions are specified).
- =nc::df_capture_first= does not prefix subject column names to
  capture group column names, whereas
  =namedCapture::df_match_variable= does.
- Internally =nc= uses un-named capture groups, whereas
  =namedCapture= uses named capture groups.
- By default the =nc::vec_capture_first= stops with an error if any
  subjects do not match, whereas =namedCapture::str_match_variable=
  returns NA/missing rows.

** Installation

#+BEGIN_SRC R
if(!require(devtools))install.packages("devtools")
devtools::install_github("tdhock/nc")
#+END_SRC

** Usage overview

There are three main functions provided in nc:

| Subject          | First match         | All matches       |
|------------------+---------------------+-------------------|
| Single string    | NA                  | =str_capture_all= |
| Character vector | =vec_capture_first= | NA                |
| Data frame       | =df_capture_first=  | NA                |

Note that these functions are analogous to the ones in namedCapture:

| namedCapture           | nc                |
|------------------------+-------------------|
| str_match_variable     | vec_capture_first |
| str_match_all_variable | str_capture_all   |
| df_match_variable      | df_capture_first  |

See my [[https://github.com/tdhock/namedCapture-article][journal paper about namedCapture]] for a usage explanation, and a
detailed comparison with other R regex packages.

** Choice of regex engine

By default, nc uses PCRE. Other options include ICU and RE2.

To tell nc that you would like to use a certain engine, 
#+BEGIN_SRC R
options(nc.engine="RE2")
#+END_SRC

Every function also has an engine argument, e.g.

#+BEGIN_SRC R
nc::vec_capture_first(engine="ICU")
#+END_SRC

