capture_first_melt_multiple <- structure(function # Capture and melt multiple columns of different types
### Extract first match of a regex from data.frame column names, by
### calling capture_first_vec on column names. Each unique value
### captured in the group named "variable" will become a column name
### in the result. Internally we call data.table::melt.data.table with
### measure.vars=a named list generated by the regex; this syntax can
### be less repetitive than using data.table::patterns.
(subject.df,
### The data.frame with column name subjects.
  ...,
### Pattern passed to capture_first_vec.
  variable.name="variable",
### Name of the column in output which has values taken from melted
### column names of input (passed to data.table::melt.data.table).
  id.vars=NULL,
### columns to use as id.vars in data.table::melt.data.table. Default
### NULL means to use all variables not matched by the pattern.
  value.factor=TRUE
### default TRUE, passed to data.table::melt.data.table.
){
  variable <- NULL
  ## Above to avoid CRAN NOTE.
  if(!is.data.frame(subject.df)){
    stop("subject must be a data.frame")
  }
  match.dt <- capture_first_vec(
    names(subject.df),
    ...,
    nomatch.error=FALSE)
  if(is.null(match.dt$variable)){
    stop("pattern must define group named variable")
  }
  no.match <- apply(is.na(match.dt), 1, all)
  if(all(no.match)){
    stop(
      "no column names match regex below\n",
      var_args_list(...)$pattern)
  }
  ##match.dt[, rep := 1:.N, by=variable] # if we wanted to join...?
  u <- match.dt[!is.na(variable), unique(variable)]
  if(is.null(id.vars)){
    id.vars <- which(! match.dt$variable %in% u)
  }
  measure.vars <- sapply(u, function(N){
    which(N == match.dt$variable)
  }, simplify=FALSE)
  melted <- melt(
    data.table(subject.df),
    value.factor=value.factor,
    id.vars=id.vars,
    variable.name=variable.name,
    measure.vars=measure.vars)
  melted
### Data table of melted/tall data, with a new column for each unique
### value of the capture group named "variable".
}, ex=function(){

  ## Example 1: melting to multiple value columns.
  library(data.table)
  (iris.dt <- data.table(i=1:nrow(iris), iris))
  iris.dt[, chr := paste(Species)]
  iris.rand <- iris.dt[sample(.N)]
  iris.wide <- cbind(first=iris.rand[1:75], second=iris.rand[76:150])
  iris.melted <- melt(iris.wide, value.factor=TRUE, measure.vars = patterns(
    i="i$",
    chr="chr$",
    Sepal.Length="Sepal.Length$",
    Sepal.Width="Sepal.Width$",
    Petal.Length="Petal.Length$",
    Petal.Width="Petal.Width$",
    Species="Species$"
  ))[order(i), names(iris.dt), with=FALSE]
  identical(iris.melted, iris.dt)

  ## nc can do the same thing -- you must define an R argument named
  ## variable, then each unique value of that group will be used to
  ## create a variable in the output data table.
  (nc.melted <- nc::capture_first_melt_multiple(
    iris.wide,
    prefix="[^.]+",
    "[.]",
    variable=".*"
  )[order(i), names(iris.dt), with=FALSE])
  identical(nc.melted, iris.dt)

  ## Example 2. Lots of column types, from example(melt.data.table).
  DT <- data.table(
    i_1 = c(1:5, NA),
    i_2 = c(NA,6:10),
    f_1 = factor(sample(c(letters[1:3], NA), 6, TRUE)),
    f_2 = factor(c("z", "a", "x", "c", "x", "x"), ordered=TRUE),
    c_1 = sample(c(letters[1:3], NA), 6, TRUE),
    d_1 = as.Date(c(1:3,NA,4:5), origin="2013-09-01"),
    d_2 = as.Date(6:1, origin="2012-01-01"))
  ## add a couple of list cols
  DT[, l_1 := DT[, list(c=list(rep(i_1, sample(5,1)))), by = i_1]$c]
  DT[, l_2 := DT[, list(c=list(rep(c_1, sample(5,1)))), by = i_1]$c]

  ## original DT syntax is quite repetitive.
  melt(DT, measure=patterns(
    i="^i",
    f="^f",
    d="^d",
    l="^l"
  ), value.factor=TRUE)

  ## nc syntax uses a single regex rather than four.
  nc::capture_first_melt_multiple(DT, variable="^[^c]")

  ## id.vars can be specified using original DT syntax.
  melt(DT, id=1:2, measure=patterns(
    f="^f",
    l="^l"
  ), value.factor=TRUE)

  ## id.vars can also be specified using nc syntax.
  nc::capture_first_melt_multiple(DT, variable="^[fl]", id.vars=1:2)

  ## Example 3, from data.table vignette.
  D2 <- fread(text="
family_id age_mother dob_child1 dob_child2 dob_child3 gender_child1 gender_child2 gender_child3
1         30 1998-11-26 2000-01-29         NA             1             2            NA
2         27 1996-06-22         NA         NA             2            NA            NA
3         26 2002-07-11 2004-04-05 2007-09-02             2             2             1
4         32 2004-10-10 2009-08-27 2012-07-21             1             1             1
5         29 2000-12-05 2005-02-28         NA             2             1            NA")
  melt(D2, variable.name="child", measure = patterns(
    dob="^dob", gender="^gender"
  ))

  ## variable.name can also be specified in nc syntax.
  nc::capture_first_melt_multiple(
    D2,
    variable="[^_]+",
    "_child",
    number="[1-3]",
    variable.name="child")

})
